### ISSUE TITLE
Mohist 1.20.1 crash by NoClassDefFoundError

### ISSUE THREAD

**Issue by MossCG** [Minecraft-LightLand/L2Library#12]
---- Minecraft Crash Report ----
// My bad.

Time: 2024-06-28 23:07:16
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.3.1-universal.jar%23289!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:37) ~[forge-1.20.1-47.3.1-universal.jar%23289!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:165) ~[server-1.20.1-20230612.114412-srg.jar%23284!/:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.1.jar%23190!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.3.1.jar%23190!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.3.1.jar%23190!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.9.jar%23102!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.9.jar%23102!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.9.jar%23102!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) [modlauncher-10.0.9.jar%23102!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) [modlauncher-10.0.9.jar%23102!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.9.jar%23102!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.9.jar%23102!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at com.mohistmc.MohistMCStart.main(MohistMCStart.java:109) [Mohist-1.20.1-build763.jar:1.20.1-763] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Suspected Mods: NONE
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:157) ~[securejarhandler-mohist-2.1.11.jar:?] {}
-- MOD l2library --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraft/server/players/PlayerList
		at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {}
		at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?] {}
		at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?] {}
		at java.lang.Class.getConstructor(Class.java:2271) ~[?:?] {}
		at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:75) ~[eventbus-6.0.5.jar%23149!/:?] {}
		at net.minecraftforge.eventbus.api.EventListenerHelper.lambda$getListenerListInternal$0(EventListenerHelper.java:56) ~[eventbus-6.0.5.jar%23149!/:?] {}
		at net.minecraftforge.eventbus.LockHelper.computeIfAbsent(LockHelper.java:61) ~[eventbus-6.0.5.jar%23149!/:?] {}
		at net.minecraftforge.eventbus.LockHelper.get(LockHelper.java:44) ~[eventbus-6.0.5.jar%23149!/:?] {}
		at net.minecraftforge.eventbus.LockHelper.computeIfAbsent(LockHelper.java:39) ~[eventbus-6.0.5.jar%23149!/:?] {}
		at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:56) ~[eventbus-6.0.5.jar%23149!/:?] {}
		at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:50) ~[eventbus-6.0.5.jar%23149!/:?] {}
		at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:279) ~[eventbus-6.0.5.jar%23149!/:?] {}
		at net.minecraftforge.eventbus.EventBus.register(EventBus.java:272) ~[eventbus-6.0.5.jar%23149!/:?] {}
		at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:166) ~[eventbus-6.0.5.jar%23149!/:?] {}
		at net.minecraftforge.eventbus.EventBus.lambda$registerClass$2(EventBus.java:89) ~[eventbus-6.0.5.jar%23149!/:?] {}
		at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
		at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
		at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
		at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?] {}
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:89) ~[eventbus-6.0.5.jar%23149!/:?] {}
		at net.minecraftforge.eventbus.EventBus.register(EventBus.java:129) ~[eventbus-6.0.5.jar%23149!/:?] {}
		at dev.xkmc.l2library.init.L2Library.<init>(L2Library.java:63) ~[l2library-2.4.25-slim.jar%23304!/:2.4.25] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:76) ~[javafmllanguage-1.20.1-47.3.1.jar%23286!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.3.1.jar%23285!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/Administrator/Desktop/Server/mods/[烧烤乐事]barbequesdelight-1.0.2.jar#272!/META-INF/jarjar/l2library-2.4.25-slim.jar
	Failure message: L2 Library (l2library) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraft/server/players/PlayerList
	Mod Version: 2.4.25
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: net.minecraft.server.players.PlayerList
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:157) ~[securejarhandler-mohist-2.1.11.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {}
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?] {}
	at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?] {}
	at java.lang.Class.getConstructor(Class.java:2271) ~[?:?] {}
	at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:75) ~[eventbus-6.0.5.jar%23149!/:?] {}
	at net.minecraftforge.eventbus.api.EventListenerHelper.lambda$getListenerListInternal$0(EventListenerHelper.java:56) ~[eventbus-6.0.5.jar%23149!/:?] {}
	at net.minecraftforge.eventbus.LockHelper.computeIfAbsent(LockHelper.java:61) ~[eventbus-6.0.5.jar%23149!/:?] {}
	at net.minecraftforge.eventbus.LockHelper.get(LockHelper.java:44) ~[eventbus-6.0.5.jar%23149!/:?] {}
	at net.minecraftforge.eventbus.LockHelper.computeIfAbsent(LockHelper.java:39) ~[eventbus-6.0.5.jar%23149!/:?] {}
	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:56) ~[eventbus-6.0.5.jar%23149!/:?] {}
	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:50) ~[eventbus-6.0.5.jar%23149!/:?] {}
	at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:279) ~[eventbus-6.0.5.jar%23149!/:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:272) ~[eventbus-6.0.5.jar%23149!/:?] {}
	at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:166) ~[eventbus-6.0.5.jar%23149!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$registerClass$2(EventBus.java:89) ~[eventbus-6.0.5.jar%23149!/:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:89) ~[eventbus-6.0.5.jar%23149!/:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:129) ~[eventbus-6.0.5.jar%23149!/:?] {}
	at dev.xkmc.l2library.init.L2Library.<init>(L2Library.java:63) ~[l2library-2.4.25-slim.jar%23304!/:2.4.25] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:76) ~[javafmllanguage-1.20.1-47.3.1.jar%23286!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.3.1.jar%23285!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Mohist Version: 1.20.1-763
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows Server 2022 (amd64) version 10.0
	Java Version: 17.0.5, Alibaba
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Alibaba
	Memory: 511217456 bytes (487 MiB) / 889192448 bytes (848 MiB) up to 10485760000 bytes (10000 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz
	Identifier: Intel64 Family 6 Model 62 Stepping 4
	Microarchitecture: Ivy Bridge (Server)
	Frequency (GHz): 3.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Microsoft Hyper-V 视频
	Graphics card #0 vendor: Microsoft
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=10.0.20348.1
	Graphics card #1 name: Microsoft Remote Display Adapter
	Graphics card #1 vendor: Microsoft
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: unknown
	Graphics card #1 versionInfo: DriverVersion=10.0.20348.1
	Memory slot #0 capacity (MB): 3968.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 12416.00
	Memory slot #1 clockSpeed (GHz): 0.00
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 19326.95
	Virtual memory used (MB): 3817.88
	Swap memory total (MB): 2944.00
	Swap memory used (MB): 0.00
	JVM Flags: 1 total; -Xmx10000M
	CraftBukkit Information: CraftServer is not running yet
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.3.1.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.1.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.3.1.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.3.1.jar mohist_implementer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.1.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.1.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar essential-loader TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		server-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: NOSIGNATURE
		[农夫乐事]FarmersDelight-1.20.1-1.2.4.jar             |Farmer's Delight              |farmersdelight                |1.20.1-1.2.4        |COMMON_SET|Manifest: NOSIGNATURE
		[前置]radiantgear-forge-2.1.5+1.20.1.jar            |Radiant Gear                  |radiantgear                   |2.1.5+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		[鼠标手势]MouseTweaks-forge-mc1.20.1-2.25.1.jar       |Mouse Tweaks                  |mousetweaks                   |2.25.1              |COMMON_SET|Manifest: NOSIGNATURE
		Female-Gender-Mod-forge-1.20.1-3.0.1.jar          |Wildfire's Female Gender Mod  |wildfire_gender               |1.20.1-3.0.1        |COMMON_SET|Manifest: NOSIGNATURE
		[玉][显示信息增强]Jade-1.20.1-forge-11.9.3.jar           |Jade                          |jade                          |11.9.3+forge        |COMMON_SET|Manifest: NOSIGNATURE
		[动作框架]player-animation-lib-forge-1.0.2-rc1+1.20.ja|Player Animator               |playeranimator                |1.0.2-rc1+1.20      |COMMON_SET|Manifest: NOSIGNATURE
		[jei]jei-1.20.1-forge-15.3.0.7.jar                |Just Enough Items             |jei                           |15.3.0.7            |COMMON_SET|Manifest: NOSIGNATURE
		[更真实的第一人称模型]firstperson-forge-2.4.2-mc1.20.1.jar  |FirstPerson                   |firstperson                   |2.4.2               |COMMON_SET|Manifest: NOSIGNATURE
		[拔刀剑-重锋]SlashBladeResharped-1.20.1-0.5.8.jar      |Slash Blade:Resharped         |slashblade                    |0.5.8               |COMMON_SET|Manifest: NOSIGNATURE
		[地狱乐事]nethersdelight-1.20.1-4.0.jar               |Nether's Delight              |nethersdelight                |1.20.1-4.0          |COMMON_SET|Manifest: NOSIGNATURE
		[方块信息显示]wthit-forge-8.12.0.jar                    |wthit                         |wthit                         |8.12.0              |COMMON_SET|Manifest: NOSIGNATURE
		[动态光源]dynamiclights-1.20.1.2.jar                  |Dynamic Lights                |dynamiclights                 |1.20.1.2            |COMMON_SET|Manifest: NOSIGNATURE
		[腰挂灯笼]curiouslanterns-1.20.1-1.3.2.jar            |Curious Lanterns              |curiouslanterns               |1.20.1-1.3.2        |COMMON_SET|Manifest: NOSIGNATURE
		[jei拓展]jeiintegration_1.20.1-10.0.0.jar           |JEI Integration               |jeiintegration                |10.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		[饰品栏]curios-forge-5.7.0+1.20.1.jar                |Curios API                    |curios                        |5.7.0+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		[车万女仆]touhoulittlemaid-1.20.1-release-1.1.10-hotfi|Touhou Little Maid            |touhou_little_maid            |1.1.10-hotfix       |COMMON_SET|Manifest: NOSIGNATURE
		[更多动画]notenoughanimations-forge-1.7.4-mc1.20.1.jar|NotEnoughAnimations           |notenoughanimations           |1.7.4               |COMMON_SET|Manifest: NOSIGNATURE
		[帕秋莉手册]Patchouli-1.20.1-84-FORGE.jar              |Patchouli                     |patchouli                     |1.20.1-84-FORGE     |COMMON_SET|Manifest: NOSIGNATURE
		[Xaeros的小地图]XaerosMiniMap.jar                     |Xaero's Minimap               |xaerominimap                  |24.2.0              |COMMON_SET|Manifest: NOSIGNATURE
		[Xaeros的世界地图]XaerosWorldMap_1.38.8_Forge_1.20.jar |Xaero's World Map             |xaeroworldmap                 |1.38.8              |COMMON_SET|Manifest: NOSIGNATURE
		[烧烤乐事]barbequesdelight-1.0.2.jar                  |Barbeque's Delight            |barbequesdelight              |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		[框架前置]badpackets-forge-0.4.3.jar                  |Bad Packets                   |badpackets                    |0.4.3               |COMMON_SET|Manifest: NOSIGNATURE
		[实体渲染机制优化] entityculling-forge-1.6.6-mc1.20.1.jar |EntityCulling                 |entityculling                 |1.6.6               |COMMON_SET|Manifest: NOSIGNATURE
		mixinextras-forge-0.3.6.jar                       |MixinExtras                   |mixinextras                   |0.3.6               |COMMON_SET|Manifest: NOSIGNATURE
		[屠夫乐事]Butchersdelight beta 1.20.1 2.1.0.jar       |ButchersDelight               |butchersdelight               |1.20.12.1.0         |COMMON_SET|Manifest: NOSIGNATURE
		[简易飞机]simpleplanes-1.20.1-5.2.7.jar               |Simple Planes                 |simpleplanes                  |1.20.1-5.2.7        |COMMON_SET|Manifest: NOSIGNATURE
		[星光]starlight-1.1.2+forge.1cda73c.jar             |Starlight                     |starlight                     |1.1.2+forge.1cda73c |COMMON_SET|Manifest: NOSIGNATURE
		[下届乐事]ends_delight-1.20.1-2.2.jar                 |End's Delight                 |ends_delight                  |2.2                 |COMMON_SET|Manifest: NOSIGNATURE
		cfm-forge-1.20.1-7.0.0-pre36.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre36         |COMMON_SET|Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		architectury-9.2.14-forge.jar                     |Architectury                  |architectury                  |9.2.14              |COMMON_SET|Manifest: NOSIGNATURE
		[凤梨乐事]PineappleDelight-Forge-1.20-1.0.8-Fix.jar   |Pineapple Delight             |pineapple_delight             |1.0.8               |COMMON_SET|Manifest: NOSIGNATURE
		l2library-2.4.25-slim.jar                         |L2 Library                    |l2library                     |2.4.25              |ERROR     |Manifest: NOSIGNATURE
		cloth-config-11.1.118-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.118            |COMMON_SET|Manifest: NOSIGNATURE
		[1.20.1-forge]-Epic-Knights-9.8.jar               |Epic Knights Mod              |magistuarmory                 |9.8                 |COMMON_SET|Manifest: NOSIGNATURE
		[1.20.x-forge]-Epic-Knights-Addon-1.6.jar         |Epic Knights: Addon           |magistuarmoryaddon            |1.6                 |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.20.1-47.3.1-universal.jar                 |Forge                         |forge                         |47.3.1              |COMMON_SET|Manifest: NOSIGNATURE
		[剪刀]dontcuttripwire-1.20.1-0.2.0.jar              |DontCutTripwire               |dontcuttripwire               |0.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		[暮色森林]twilightforest-1.20.1-4.3.2508-universal.jar|The Twilight Forest           |twilightforest                |4.3.2508            |COMMON_SET|Manifest: NOSIGNATURE
		(与rubidium不兼容)embeddium-0.3.11+mc1.20.1.jar       |Embeddium                     |embeddium                     |0.3.11+mc1.20.1     |COMMON_SET|Manifest: NOSIGNATURE
		Essential (forge_1.20.1).jar                      |Essential                     |essential                     |1.3.2.6+g1d9edc32b7 |COMMON_SET|Manifest: NOSIGNATURE
		[更好的延迟显示]BetterPingDisplay-1.20.1-1.1.jar         |Better Ping Display           |betterpingdisplay             |1.1                 |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 7ad70e52-898a-4408-be2f-fc2ad02759ae
	FML: 0.0
	Forge: net.minecraftforge:47.3.1

**Comment by lcy0x1** [comment]
Mohist把一个原版代码PlayerList删了，导致莱特兰找不到。也有可能是其他mod崩溃了导致Mohist没能处理加载，从而导致PlayerList没法被找到
